// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: control.proto

package controlv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentControlService_Session_FullMethodName = "/stressbot.control.v1.AgentControlService/Session"
)

// AgentControlServiceClient is the client API for AgentControlService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgentControlServiceClient interface {
	Session(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentEvent, AdminEvent], error)
}

type agentControlServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentControlServiceClient(cc grpc.ClientConnInterface) AgentControlServiceClient {
	return &agentControlServiceClient{cc}
}

func (c *agentControlServiceClient) Session(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentEvent, AdminEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentControlService_ServiceDesc.Streams[0], AgentControlService_Session_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AgentEvent, AdminEvent]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentControlService_SessionClient = grpc.BidiStreamingClient[AgentEvent, AdminEvent]

// AgentControlServiceServer is the server API for AgentControlService service.
// All implementations must embed UnimplementedAgentControlServiceServer
// for forward compatibility.
type AgentControlServiceServer interface {
	Session(grpc.BidiStreamingServer[AgentEvent, AdminEvent]) error
	mustEmbedUnimplementedAgentControlServiceServer()
}

// UnimplementedAgentControlServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentControlServiceServer struct{}

func (UnimplementedAgentControlServiceServer) Session(grpc.BidiStreamingServer[AgentEvent, AdminEvent]) error {
	return status.Error(codes.Unimplemented, "method Session not implemented")
}
func (UnimplementedAgentControlServiceServer) mustEmbedUnimplementedAgentControlServiceServer() {}
func (UnimplementedAgentControlServiceServer) testEmbeddedByValue()                             {}

// UnsafeAgentControlServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentControlServiceServer will
// result in compilation errors.
type UnsafeAgentControlServiceServer interface {
	mustEmbedUnimplementedAgentControlServiceServer()
}

func RegisterAgentControlServiceServer(s grpc.ServiceRegistrar, srv AgentControlServiceServer) {
	// If the following call panics, it indicates UnimplementedAgentControlServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentControlService_ServiceDesc, srv)
}

func _AgentControlService_Session_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentControlServiceServer).Session(&grpc.GenericServerStream[AgentEvent, AdminEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentControlService_SessionServer = grpc.BidiStreamingServer[AgentEvent, AdminEvent]

// AgentControlService_ServiceDesc is the grpc.ServiceDesc for AgentControlService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentControlService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "stressbot.control.v1.AgentControlService",
	HandlerType: (*AgentControlServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Session",
			Handler:       _AgentControlService_Session_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "control.proto",
}

const (
	AgentBundleService_DownloadBundle_FullMethodName = "/stressbot.control.v1.AgentBundleService/DownloadBundle"
)

// AgentBundleServiceClient is the client API for AgentBundleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgentBundleServiceClient interface {
	DownloadBundle(ctx context.Context, in *BundleRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BundleChunk], error)
}

type agentBundleServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentBundleServiceClient(cc grpc.ClientConnInterface) AgentBundleServiceClient {
	return &agentBundleServiceClient{cc}
}

func (c *agentBundleServiceClient) DownloadBundle(ctx context.Context, in *BundleRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BundleChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentBundleService_ServiceDesc.Streams[0], AgentBundleService_DownloadBundle_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[BundleRequest, BundleChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentBundleService_DownloadBundleClient = grpc.ServerStreamingClient[BundleChunk]

// AgentBundleServiceServer is the server API for AgentBundleService service.
// All implementations must embed UnimplementedAgentBundleServiceServer
// for forward compatibility.
type AgentBundleServiceServer interface {
	DownloadBundle(*BundleRequest, grpc.ServerStreamingServer[BundleChunk]) error
	mustEmbedUnimplementedAgentBundleServiceServer()
}

// UnimplementedAgentBundleServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentBundleServiceServer struct{}

func (UnimplementedAgentBundleServiceServer) DownloadBundle(*BundleRequest, grpc.ServerStreamingServer[BundleChunk]) error {
	return status.Error(codes.Unimplemented, "method DownloadBundle not implemented")
}
func (UnimplementedAgentBundleServiceServer) mustEmbedUnimplementedAgentBundleServiceServer() {}
func (UnimplementedAgentBundleServiceServer) testEmbeddedByValue()                            {}

// UnsafeAgentBundleServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentBundleServiceServer will
// result in compilation errors.
type UnsafeAgentBundleServiceServer interface {
	mustEmbedUnimplementedAgentBundleServiceServer()
}

func RegisterAgentBundleServiceServer(s grpc.ServiceRegistrar, srv AgentBundleServiceServer) {
	// If the following call panics, it indicates UnimplementedAgentBundleServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentBundleService_ServiceDesc, srv)
}

func _AgentBundleService_DownloadBundle_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(BundleRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AgentBundleServiceServer).DownloadBundle(m, &grpc.GenericServerStream[BundleRequest, BundleChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentBundleService_DownloadBundleServer = grpc.ServerStreamingServer[BundleChunk]

// AgentBundleService_ServiceDesc is the grpc.ServiceDesc for AgentBundleService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentBundleService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "stressbot.control.v1.AgentBundleService",
	HandlerType: (*AgentBundleServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "DownloadBundle",
			Handler:       _AgentBundleService_DownloadBundle_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "control.proto",
}

const (
	AgentTelemetryService_Report_FullMethodName = "/stressbot.control.v1.AgentTelemetryService/Report"
)

// AgentTelemetryServiceClient is the client API for AgentTelemetryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgentTelemetryServiceClient interface {
	Report(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[TelemetryEnvelope, TelemetryClose], error)
}

type agentTelemetryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentTelemetryServiceClient(cc grpc.ClientConnInterface) AgentTelemetryServiceClient {
	return &agentTelemetryServiceClient{cc}
}

func (c *agentTelemetryServiceClient) Report(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[TelemetryEnvelope, TelemetryClose], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentTelemetryService_ServiceDesc.Streams[0], AgentTelemetryService_Report_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TelemetryEnvelope, TelemetryClose]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentTelemetryService_ReportClient = grpc.ClientStreamingClient[TelemetryEnvelope, TelemetryClose]

// AgentTelemetryServiceServer is the server API for AgentTelemetryService service.
// All implementations must embed UnimplementedAgentTelemetryServiceServer
// for forward compatibility.
type AgentTelemetryServiceServer interface {
	Report(grpc.ClientStreamingServer[TelemetryEnvelope, TelemetryClose]) error
	mustEmbedUnimplementedAgentTelemetryServiceServer()
}

// UnimplementedAgentTelemetryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentTelemetryServiceServer struct{}

func (UnimplementedAgentTelemetryServiceServer) Report(grpc.ClientStreamingServer[TelemetryEnvelope, TelemetryClose]) error {
	return status.Error(codes.Unimplemented, "method Report not implemented")
}
func (UnimplementedAgentTelemetryServiceServer) mustEmbedUnimplementedAgentTelemetryServiceServer() {}
func (UnimplementedAgentTelemetryServiceServer) testEmbeddedByValue()                               {}

// UnsafeAgentTelemetryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentTelemetryServiceServer will
// result in compilation errors.
type UnsafeAgentTelemetryServiceServer interface {
	mustEmbedUnimplementedAgentTelemetryServiceServer()
}

func RegisterAgentTelemetryServiceServer(s grpc.ServiceRegistrar, srv AgentTelemetryServiceServer) {
	// If the following call panics, it indicates UnimplementedAgentTelemetryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentTelemetryService_ServiceDesc, srv)
}

func _AgentTelemetryService_Report_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentTelemetryServiceServer).Report(&grpc.GenericServerStream[TelemetryEnvelope, TelemetryClose]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentTelemetryService_ReportServer = grpc.ClientStreamingServer[TelemetryEnvelope, TelemetryClose]

// AgentTelemetryService_ServiceDesc is the grpc.ServiceDesc for AgentTelemetryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentTelemetryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "stressbot.control.v1.AgentTelemetryService",
	HandlerType: (*AgentTelemetryServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Report",
			Handler:       _AgentTelemetryService_Report_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "control.proto",
}
