syntax = "proto3"; //[proto2|proto3]

option go_package = ".;pb";
package Game;

// 单模式活动赛 //////////////////////////////////////////////////////////////////////////////////////////////////
// 单模式活动赛 //////////////////////////////////////////////////////////////////////////////////////////////////
// 单模式活动赛 //////////////////////////////////////////////////////////////////////////////////////////////////

// 单模式活动赛玩家数据
message ActivityBattleSingleDbInfo {
  int32 failTimes = 1;  // 失败次数
  int32 buyFailTimes = 2;  // 购买的失败次数
  int32 victoryTimes = 3;  // 胜利场数
  map<int32, bool> victoryReward = 4; // 胜场奖励领取记录
  int64 endTimestamp = 5; // 本期结束时间
  int32 nowId = 6; // 当前期数配置id
}
