syntax = "proto3"; //[proto2|proto3]

option go_package = ".;pb";
package Game;

// 活动赛 //////////////////////////////////////////////////////////////////////////////////////////////////
// 活动赛 //////////////////////////////////////////////////////////////////////////////////////////////////
// 活动赛 //////////////////////////////////////////////////////////////////////////////////////////////////

// 玩家活动赛数据
message ActivityBattleDbInfo {
  int32 failTimes = 1;  // 失败次数
  int32 buyFailTimes = 2;  // 购买的失败次数
  int32 victoryTimes = 3;  // 胜利场数
  int32 nowStep = 4; // 当前阶段  虽然可以用胜场直接计算
  map<int32, bool> victoryReward = 5; // 胜场奖励领取记录
  int64 endTimestamp = 6; // 本期结束时间
  int32 selectStep = 7; // 选择的阶段
  int32 nowId = 8; // 当前活动赛期数配置id
}

