// Package managementapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package managementapi

import (
	"encoding/json"
	"fmt"
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// CapabilitiesResponse defines model for CapabilitiesResponse.
type CapabilitiesResponse struct {
	FlowLibrary     bool    `json:"flowLibrary"`
	SharedAddr      *string `json:"sharedAddr,omitempty"`
	SharedState     bool    `json:"sharedState"`
	TemplateLibrary bool    `json:"templateLibrary"`
}

// ManagementApiError defines model for ManagementApiError.
type ManagementApiError struct {
	Code                 string                 `json:"code"`
	Details              interface{}            `json:"details,omitempty"`
	Message              string                 `json:"message"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// Id defines model for Id.
type Id = string

// Name defines model for Name.
type Name = string

// ResourcePath defines model for ResourcePath.
type ResourcePath = string

// BadRequest defines model for BadRequest.
type BadRequest = ManagementApiError

// Conflict defines model for Conflict.
type Conflict = ManagementApiError

// FileOK defines model for FileOK.
type FileOK = interface{}

// JsonCreated defines model for JsonCreated.
type JsonCreated = interface{}

// JsonOK defines model for JsonOK.
type JsonOK = interface{}

// NotFound defines model for NotFound.
type NotFound = ManagementApiError

// ServerError defines model for ServerError.
type ServerError = ManagementApiError

// JsonObject defines model for JsonObject.
type JsonObject map[string]interface{}

// OptionalJsonObject defines model for OptionalJsonObject.
type OptionalJsonObject map[string]interface{}

// CreateActionTemplateJSONBody defines parameters for CreateActionTemplate.
type CreateActionTemplateJSONBody map[string]interface{}

// ReplaceActionTemplateSnapshotJSONBody defines parameters for ReplaceActionTemplateSnapshot.
type ReplaceActionTemplateSnapshotJSONBody map[string]interface{}

// UpdateActionTemplateJSONBody defines parameters for UpdateActionTemplate.
type UpdateActionTemplateJSONBody map[string]interface{}

// PreviewCodecJSONBody defines parameters for PreviewCodec.
type PreviewCodecJSONBody map[string]interface{}

// CreateFlowJSONBody defines parameters for CreateFlow.
type CreateFlowJSONBody map[string]interface{}

// ReplaceFlowSnapshotJSONBody defines parameters for ReplaceFlowSnapshot.
type ReplaceFlowSnapshotJSONBody map[string]interface{}

// UpdateFlowJSONBody defines parameters for UpdateFlow.
type UpdateFlowJSONBody map[string]interface{}

// UpdateHistoryJSONBody defines parameters for UpdateHistory.
type UpdateHistoryJSONBody map[string]interface{}

// CloneHistoryJSONBody defines parameters for CloneHistory.
type CloneHistoryJSONBody map[string]interface{}

// CreateListenTemplateJSONBody defines parameters for CreateListenTemplate.
type CreateListenTemplateJSONBody map[string]interface{}

// ReplaceListenTemplateSnapshotJSONBody defines parameters for ReplaceListenTemplateSnapshot.
type ReplaceListenTemplateSnapshotJSONBody map[string]interface{}

// UpdateListenTemplateJSONBody defines parameters for UpdateListenTemplate.
type UpdateListenTemplateJSONBody map[string]interface{}

// CreateTaskMultipartBody defines parameters for CreateTask.
type CreateTaskMultipartBody struct {
	Deadline             *time.Time             `json:"deadline,omitempty"`
	FlowJson             openapi_types.File     `json:"flow.json"`
	FlowTemplateId       *string                `json:"flowTemplateId,omitempty"`
	Name                 string                 `json:"name"`
	RobotConfig          *string                `json:"robotConfig,omitempty"`
	TotalBots            int                    `json:"totalBots"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// CreateActionTemplateJSONRequestBody defines body for CreateActionTemplate for application/json ContentType.
type CreateActionTemplateJSONRequestBody CreateActionTemplateJSONBody

// ReplaceActionTemplateSnapshotJSONRequestBody defines body for ReplaceActionTemplateSnapshot for application/json ContentType.
type ReplaceActionTemplateSnapshotJSONRequestBody ReplaceActionTemplateSnapshotJSONBody

// UpdateActionTemplateJSONRequestBody defines body for UpdateActionTemplate for application/json ContentType.
type UpdateActionTemplateJSONRequestBody UpdateActionTemplateJSONBody

// PreviewCodecJSONRequestBody defines body for PreviewCodec for application/json ContentType.
type PreviewCodecJSONRequestBody PreviewCodecJSONBody

// CreateFlowJSONRequestBody defines body for CreateFlow for application/json ContentType.
type CreateFlowJSONRequestBody CreateFlowJSONBody

// ReplaceFlowSnapshotJSONRequestBody defines body for ReplaceFlowSnapshot for application/json ContentType.
type ReplaceFlowSnapshotJSONRequestBody ReplaceFlowSnapshotJSONBody

// UpdateFlowJSONRequestBody defines body for UpdateFlow for application/json ContentType.
type UpdateFlowJSONRequestBody UpdateFlowJSONBody

// UpdateHistoryJSONRequestBody defines body for UpdateHistory for application/json ContentType.
type UpdateHistoryJSONRequestBody UpdateHistoryJSONBody

// CloneHistoryJSONRequestBody defines body for CloneHistory for application/json ContentType.
type CloneHistoryJSONRequestBody CloneHistoryJSONBody

// CreateListenTemplateJSONRequestBody defines body for CreateListenTemplate for application/json ContentType.
type CreateListenTemplateJSONRequestBody CreateListenTemplateJSONBody

// ReplaceListenTemplateSnapshotJSONRequestBody defines body for ReplaceListenTemplateSnapshot for application/json ContentType.
type ReplaceListenTemplateSnapshotJSONRequestBody ReplaceListenTemplateSnapshotJSONBody

// UpdateListenTemplateJSONRequestBody defines body for UpdateListenTemplate for application/json ContentType.
type UpdateListenTemplateJSONRequestBody UpdateListenTemplateJSONBody

// CreateTaskMultipartRequestBody defines body for CreateTask for multipart/form-data ContentType.
type CreateTaskMultipartRequestBody CreateTaskMultipartBody

// Getter for additional properties for ManagementApiError. Returns the specified
// element and whether it was found
func (a ManagementApiError) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for ManagementApiError
func (a *ManagementApiError) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for ManagementApiError to handle AdditionalProperties
func (a *ManagementApiError) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["code"]; found {
		err = json.Unmarshal(raw, &a.Code)
		if err != nil {
			return fmt.Errorf("error reading 'code': %w", err)
		}
		delete(object, "code")
	}

	if raw, found := object["details"]; found {
		err = json.Unmarshal(raw, &a.Details)
		if err != nil {
			return fmt.Errorf("error reading 'details': %w", err)
		}
		delete(object, "details")
	}

	if raw, found := object["message"]; found {
		err = json.Unmarshal(raw, &a.Message)
		if err != nil {
			return fmt.Errorf("error reading 'message': %w", err)
		}
		delete(object, "message")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for ManagementApiError to handle AdditionalProperties
func (a ManagementApiError) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["code"], err = json.Marshal(a.Code)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'code': %w", err)
	}

	object["details"], err = json.Marshal(a.Details)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'details': %w", err)
	}

	object["message"], err = json.Marshal(a.Message)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'message': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for CreateTaskMultipartBody. Returns the specified
// element and whether it was found
func (a CreateTaskMultipartBody) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for CreateTaskMultipartBody
func (a *CreateTaskMultipartBody) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for CreateTaskMultipartBody to handle AdditionalProperties
func (a *CreateTaskMultipartBody) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["deadline"]; found {
		err = json.Unmarshal(raw, &a.Deadline)
		if err != nil {
			return fmt.Errorf("error reading 'deadline': %w", err)
		}
		delete(object, "deadline")
	}

	if raw, found := object["flow.json"]; found {
		err = json.Unmarshal(raw, &a.FlowJson)
		if err != nil {
			return fmt.Errorf("error reading 'flow.json': %w", err)
		}
		delete(object, "flow.json")
	}

	if raw, found := object["flowTemplateId"]; found {
		err = json.Unmarshal(raw, &a.FlowTemplateId)
		if err != nil {
			return fmt.Errorf("error reading 'flowTemplateId': %w", err)
		}
		delete(object, "flowTemplateId")
	}

	if raw, found := object["name"]; found {
		err = json.Unmarshal(raw, &a.Name)
		if err != nil {
			return fmt.Errorf("error reading 'name': %w", err)
		}
		delete(object, "name")
	}

	if raw, found := object["robotConfig"]; found {
		err = json.Unmarshal(raw, &a.RobotConfig)
		if err != nil {
			return fmt.Errorf("error reading 'robotConfig': %w", err)
		}
		delete(object, "robotConfig")
	}

	if raw, found := object["totalBots"]; found {
		err = json.Unmarshal(raw, &a.TotalBots)
		if err != nil {
			return fmt.Errorf("error reading 'totalBots': %w", err)
		}
		delete(object, "totalBots")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for CreateTaskMultipartBody to handle AdditionalProperties
func (a CreateTaskMultipartBody) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Deadline != nil {
		object["deadline"], err = json.Marshal(a.Deadline)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'deadline': %w", err)
		}
	}

	object["flow.json"], err = json.Marshal(a.FlowJson)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'flow.json': %w", err)
	}

	if a.FlowTemplateId != nil {
		object["flowTemplateId"], err = json.Marshal(a.FlowTemplateId)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'flowTemplateId': %w", err)
		}
	}

	object["name"], err = json.Marshal(a.Name)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'name': %w", err)
	}

	if a.RobotConfig != nil {
		object["robotConfig"], err = json.Marshal(a.RobotConfig)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'robotConfig': %w", err)
		}
	}

	object["totalBots"], err = json.Marshal(a.TotalBots)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'totalBots': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}
